// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pb/orders.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A drink that can be ordered
type Drink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drink) Reset() {
	*x = Drink{}
	mi := &file_pb_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drink) ProtoMessage() {}

func (x *Drink) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drink.ProtoReflect.Descriptor instead.
func (*Drink) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Drink) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Drink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Drink) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Drink) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Response for GetDrinks: list of all drinks
type ListDrinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drinks        []*Drink               `protobuf:"bytes,1,rep,name=drinks,proto3" json:"drinks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDrinksResponse) Reset() {
	*x = ListDrinksResponse{}
	mi := &file_pb_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDrinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDrinksResponse) ProtoMessage() {}

func (x *ListDrinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDrinksResponse.ProtoReflect.Descriptor instead.
func (*ListDrinksResponse) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{1}
}

func (x *ListDrinksResponse) GetDrinks() []*Drink {
	if x != nil {
		return x.Drinks
	}
	return nil
}

// Request for OrderDrink
type OrderDrinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrinkId       int32                  `protobuf:"varint,1,opt,name=drink_id,json=drinkId,proto3" json:"drink_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDrinkRequest) Reset() {
	*x = OrderDrinkRequest{}
	mi := &file_pb_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDrinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDrinkRequest) ProtoMessage() {}

func (x *OrderDrinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDrinkRequest.ProtoReflect.Descriptor instead.
func (*OrderDrinkRequest) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{2}
}

func (x *OrderDrinkRequest) GetDrinkId() int32 {
	if x != nil {
		return x.DrinkId
	}
	return 0
}

func (x *OrderDrinkRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Response for OrderDrink
type OrderDrinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderDrinkResponse) Reset() {
	*x = OrderDrinkResponse{}
	mi := &file_pb_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDrinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDrinkResponse) ProtoMessage() {}

func (x *OrderDrinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDrinkResponse.ProtoReflect.Descriptor instead.
func (*OrderDrinkResponse) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{3}
}

func (x *OrderDrinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OrderDrinkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Single order line (used in GetOrdersResponse)
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DrinkId       int32                  `protobuf:"varint,1,opt,name=drink_id,json=drinkId,proto3" json:"drink_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_pb_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetDrinkId() int32 {
	if x != nil {
		return x.DrinkId
	}
	return 0
}

func (x *Order) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Response for GetOrders: aggregated totals per drink
type GetOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_pb_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_pb_orders_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_pb_orders_proto protoreflect.FileDescriptor

const file_pb_orders_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/orders.proto\x12\x06models\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"c\n" +
	"\x05Drink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\";\n" +
	"\x12ListDrinksResponse\x12%\n" +
	"\x06drinks\x18\x01 \x03(\v2\r.models.DrinkR\x06drinks\"F\n" +
	"\x11OrderDrinkRequest\x12\x19\n" +
	"\bdrink_id\x18\x01 \x01(\x05R\adrinkId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"H\n" +
	"\x12OrderDrinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x05Order\x12\x19\n" +
	"\bdrink_id\x18\x01 \x01(\x05R\adrinkId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\":\n" +
	"\x11GetOrdersResponse\x12%\n" +
	"\x06orders\x18\x01 \x03(\v2\r.models.OrderR\x06orders2\xd4\x01\n" +
	"\fOrderService\x12?\n" +
	"\tGetDrinks\x12\x16.google.protobuf.Empty\x1a\x1a.models.ListDrinksResponse\x12C\n" +
	"\n" +
	"OrderDrink\x12\x19.models.OrderDrinkRequest\x1a\x1a.models.OrderDrinkResponse\x12>\n" +
	"\tGetOrders\x12\x16.google.protobuf.Empty\x1a\x19.models.GetOrdersResponseB\tZ\aexc8/pbb\x06proto3"

var (
	file_pb_orders_proto_rawDescOnce sync.Once
	file_pb_orders_proto_rawDescData []byte
)

func file_pb_orders_proto_rawDescGZIP() []byte {
	file_pb_orders_proto_rawDescOnce.Do(func() {
		file_pb_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_orders_proto_rawDesc), len(file_pb_orders_proto_rawDesc)))
	})
	return file_pb_orders_proto_rawDescData
}

var file_pb_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_orders_proto_goTypes = []any{
	(*Drink)(nil),              // 0: models.Drink
	(*ListDrinksResponse)(nil), // 1: models.ListDrinksResponse
	(*OrderDrinkRequest)(nil),  // 2: models.OrderDrinkRequest
	(*OrderDrinkResponse)(nil), // 3: models.OrderDrinkResponse
	(*Order)(nil),              // 4: models.Order
	(*GetOrdersResponse)(nil),  // 5: models.GetOrdersResponse
	(*emptypb.Empty)(nil),      // 6: google.protobuf.Empty
}
var file_pb_orders_proto_depIdxs = []int32{
	0, // 0: models.ListDrinksResponse.drinks:type_name -> models.Drink
	4, // 1: models.GetOrdersResponse.orders:type_name -> models.Order
	6, // 2: models.OrderService.GetDrinks:input_type -> google.protobuf.Empty
	2, // 3: models.OrderService.OrderDrink:input_type -> models.OrderDrinkRequest
	6, // 4: models.OrderService.GetOrders:input_type -> google.protobuf.Empty
	1, // 5: models.OrderService.GetDrinks:output_type -> models.ListDrinksResponse
	3, // 6: models.OrderService.OrderDrink:output_type -> models.OrderDrinkResponse
	5, // 7: models.OrderService.GetOrders:output_type -> models.GetOrdersResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_orders_proto_init() }
func file_pb_orders_proto_init() {
	if File_pb_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_orders_proto_rawDesc), len(file_pb_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_orders_proto_goTypes,
		DependencyIndexes: file_pb_orders_proto_depIdxs,
		MessageInfos:      file_pb_orders_proto_msgTypes,
	}.Build()
	File_pb_orders_proto = out.File
	file_pb_orders_proto_goTypes = nil
	file_pb_orders_proto_depIdxs = nil
}
